-- 코드를 작성해주세요
select I.ITEM_ID, I.ITEM_NAME, I.RARITY
from ITEM_INFO I
WHERE EXISTS(
    SELECT 1
    FROM ITEM_INFO P
    JOIN ITEM_TREE T ON P.ITEM_ID = T.PARENT_ITEM_ID
    WHERE T.ITEM_ID = I.ITEM_ID 
    AND P.RARITY = 'RARE')
ORDER BY I.ITEM_ID DESC
